export const FETCH_MYSTOCK = 'FETCH_MYSTOCK';
export const FETCH_STOCK = 'FETCH_STOCK';
export const FETCH_DETAIL_STOCK = 'FETCH_DETAIL_STOCK';
export const FETCH_STOCK_NOT_FOUND ='FETCH_STOCK_NOT_FOUND';
